app/controllers/__init__.py
from datetime import datetime
from datetime import date

from flask import Flask, redirect, url_for, abort
from flask import Blueprint

blueprint = Blueprint('__init__', __name__, url_prefix='/')


@blueprint.route("")
def main_api():
    return redirect(url_for('bus.list_api'))


@blueprint.route("<int:campus_id>")
def _campus_api(campus_id):
    return redirect(url_for('bus.list_api'))

app/controllers/bus/__init__.py
from datetime import datetime
from datetime import date

from flask import Flask, render_template, redirect, url_for, abort
from flask import Blueprint
from flask import request

from ...func import firebase_api
from ...func.weekday import get_weekday, put_weekday

blueprint = Blueprint('bus', __name__, url_prefix='/buses')


@blueprint.route("")
def list_api():
    return render_template(
        "bus/list_api.html",
        buses=firebase_api.bus_list_api(),
        weekday=get_weekday(),
        bus_updated_datetime=firebase_api.get_updated_datetime())


@blueprint.route("/<int:bus_id>")
def detail_api(bus_id):
    bus = firebase_api.bus_detail_api(bus_id)
    if bus is None:
        abort(404)

    return render_template(
        "bus/detail_api.html",
        buses=firebase_api.bus_list_api(),
        bus=bus,
        weekday=get_weekday(),
        bus_updated_datetime=firebase_api.get_updated_datetime())


@blueprint.route("/weekday")
def weekday_api():
    data = request.args

    weekday = data.get('weekday', None, type=int)
    if weekday is not None:
        put_weekday(weekday)

    next_url = data.get('next_url', None)
    return redirect(next_url)

app/controllers/feedback/__init__.py
from datetime import datetime
from datetime import date

from flask import Flask, render_template, redirect, url_for, abort
from flask import Blueprint
from flask import request
from flask import flash

from ...func import slack

blueprint = Blueprint('feedback', __name__, url_prefix='/feedbacks')


@blueprint.route("", methods=["POST"])
def add_api():
    data = request.form
    description = data.get('description', None)
    if not description:
        description = ''
    description = description.strip()
    if description:
        slack.post_feedback(description)
        flash('성공적으로 피드백이 전송되었습니다.')
    else:
        flash('피드백 내용을 입력해 주세요.')

    next_url = request.args.get('next_url', None)
    return redirect(next_url)

app/controllers/line/__init__.py
from datetime import datetime
from datetime import date

from flask import Flask, redirect, url_for, abort
from flask import Blueprint

blueprint = Blueprint('line', __name__, url_prefix='/line')


@blueprint.route("")
def list_api():
    return redirect(url_for('bus.list_api'))


@blueprint.route("/<int:line_id>")
def detail_api(line_id):
    return redirect(url_for('bus.list_api'))

app/templates/__base__.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}KAIST 버스{% endblock %}</title>

    {% block extraheader %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/SpoqaHanSans-kr.css') }}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bus-web.0.0.1.css') }}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/themes/white/pace-theme-minimal.min.css" />
    {% endblock %}
  </head>

  <body>
		{% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
      <a class="navbar-brand" href="{{ url_for('__init__.main_api') }}">
        KAIST 버스
      </a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#busNavbar" aria-controls="busNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="busNavbar">
        <ul class="navbar-nav mr-auto">
          {% for bus in buses %}
          {% if bus.id <= 3 %}
          <li class="nav-item {% if request.endpoint == 'bus.detail_api' and request.view_args.get('bus_id') == bus.id %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('bus.detail_api', bus_id=bus.id) }}">{{ bus.name }}</a>
          </li>
          {% endif %}
          {% endfor %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle {% if request.endpoint == 'bus.detail_api' and request.view_args.get('bus_id') > 3 %}active{% endif %}" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              노선 더보기
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for bus in buses %}
              {% if bus.id > 3 %}
              <a class="dropdown-item {% if request.endpoint == 'bus.detail_api' and request.view_args.get('bus_id') == bus.id %}active{% endif %}" href="{{ url_for('bus.detail_api', bus_id=bus.id) }}">{{ bus.name }}</a>
              {% endif %}
              {% endfor %}
            </div>
          </li>
        </ul>
        <ul class="navbar-nav navbar-right">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% if weekday < 5 %}평일{% else %}휴일{% endif %}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item {% if weekday < 5 %}active{% endif %}" href="{{ url_for('bus.weekday_api', weekday=0, next_url=request.path) }}">평일 시간표</a>
              <a class="dropdown-item {% if weekday >= 5 %}active{% endif %}" href="{{ url_for('bus.weekday_api', weekday=5, next_url=request.path) }}">휴일 시간표</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#" data-toggle="modal" data-target="#feedback-modal">피드백</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
		{% endblock %}

		<div class="container">
      {% block container %}
			{% endblock %}
		</div>

    {% block modal %}
    <!-- Modal -->
    <form action="{{ url_for('feedback.add_api', next_url=request.path) }}" method="post">
      <div class="modal fade" id="feedback-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">피드백</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>

            <div class="modal-body">
              <div class="input-group">
                <textarea type="text" name="description" class="form-control" placeholder="피드백 내용을 입력해 주세요."></textarea>
              </div>
            </div>
            <div class="modal-footer">
              <button type="submit" class="btn btn-primary text-white">확인</button>
              <button class="btn btn-secondary text-white" data-dismiss="modal">닫기</button>
            </div>
          </div>
        </div>
      </div>
    </form>
    {% endblock %}

		{% block script %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datejs/1.0/date.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-43718027-1', 'kaist.ac.kr');
      ga('send', 'pageview');

    </script>
    <script>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
      toastr.info("{{ message }}");
    {% endfor %}
    {% endif %}
    {% endwith %}
    </script>
		{% endblock %}
	</body>
</html>

app/templates/__base__/_feedback.html
<p class="text-center bus-report">
  <a href="#" data-toggle="modal" data-target="#feedback-modal">
    <u>시간표가 잘못됐다면, 제보해주세요!</u>
  </a><br/>
  <small class="text-secondary">(최근 시간표 업데이트: {{ bus_updated_datetime }})</small>
</p>

app/templates/bus/detail_api.html
{% extends '__base__.html' %}

{% block title %}KAIST 버스 - {{ bus.name }}{% endblock %}

{% block container %}
<div class="row">
  <div class="col-12">
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      {% for station in bus.stations %}
      <li class="nav-item">
        <a class="nav-link {% if loop.index == 1 %}active{% endif %}" id="pills-{{ station.id }}-tab" data-toggle="pill" href="#pills-{{ station.id }}" role="tab" aria-controls="pills-{{ station.id }}" aria-selected="true">
          {{ station.name }}
          <br/>
          <small><i class="fa fa-angle-right" aria-hidden="true"></i> {{ station.direction_name }}</small>
        </a>
      </li>
      {% endfor %}
    </ul>

    <div class="tab-content" id="pills-tabContent">
      {% for station in bus.stations %}
      <div class="tab-pane fade {% if loop.index == 1%}show active{% endif %}" id="pills-{{ station.id }}" role="tabpanel" aria-labelledby="pills-{{ station.id }}-tab">
        <ul class="list-group">
          {% for time in station.times[weekday|string] %}
          <li class="list-group-item">
            <div class="row">
              <div class="col-6">{{ time }}</div>
              <div class="bus-left-time col-6 text-right text-secondary" data-time="{{ time }}">
                <i class="fa fa-spinner" aria-hidden="true"></i>
              </div>
            </div>
          </li>
          {% else %}
          <li class="list-group-item inactive">운행정보가 없습니다.</li>
          {% endfor %}
        </ul>
      </div>
      {% endfor %}
    </div>

    {% include '__base__/_feedback.html' %}
  </div>
</div>
{% endblock %}

{% block script %}
{{ super() }}
<script>
$(document).ready(function(e){
  setInterval(function(){
    $(".bus-left-time").text(function(){
      var time = $(this).data('time');
      var times = time.split(":");
      var hour = parseInt(times[0]);
      var minute = parseInt(times[1]);
      if (hour < 4){
        hour += 24;
      }
      var standard = hour * 3600 + minute * 60;

      var dt = new Date();
      var hour = dt.getHours();
      if (hour < 4){
        hour += 24;
      }
      var now = hour * 3600 + dt.getMinutes() * 60 + dt.getSeconds();
      var delta = standard - now;

      if (delta < -30) {
        $(this).html('-');
      } else if (delta < 30) {
        $(this).html('곧 도착');
      } else {
        var deltaHour = parseInt(delta / 3600);
        var deltaMinute = parseInt((delta % 3600) / 60);
        var deltaSecond = (delta % 60);
        var deltaMessage = "";
        if (deltaHour > 0) {
          deltaMessage += (deltaHour + "시간")
        }
        if (deltaMinute > 0) {
          deltaMessage += (" " + deltaMinute + "분")
        }
        if (deltaSecond > 0) {
          deltaMessage += (" " + deltaSecond + "초")
        }
        $(this).html(deltaMessage + " 전");
      }

    });
  }, 1000);
});
</script>
{% endblock %}

app/templates/bus/list_api.html
{% extends '__base__.html' %}

{% block container %}
<div class="row">
  <div class="d-none d-md-block col-12 col-md-1 col-lg-2 text-right">
    <div class="fb-like" data-href="http://bus.kaist.ac.kr/" data-layout="box_count" data-action="recommend" data-show-faces="true" data-share="true"></div>
    <p>&nbsp;</p>
    <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://bus.kaist.ac.kr/">Tweet</a>
  </div>

  <div class="col-12 col-md-10 col-lg-8">
    <div class="row">
      <div class="col-12">
        {% for bus in buses %}
        <a href="{{ url_for('bus.detail_api', bus_id=bus.get('id', 0)) }}">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ bus.get('name', '') }}</h5>
            </div>
          </div>
        </a>
        {% endfor %}

        {% include '__base__/_feedback.html' %}
      </div>

      <div class="col-12 text-center">
        <hr>
        <img src="{{ url_for('static', filename='images/include.png') }}" alt="" class="img-fluid">
        <p class="">
          <small class="text-secondary">
            이 프로젝트는 KAIST 모바일 앱개발 동아리 <a href="http://include.kaist.ac.kr" class="black-text" target="_blank" rel="noopener noreferrer">인클루드</a>의 지원을 받았습니다.<br/>
            프로젝트를 제공해주신 김동우 선배님께 감사드립니다.
          </small>
        </p>
      </div>
    </div>

    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="fb-comments" data-href="http://bus.kaist.ac.kr/" data-numposts="7" data-width="100%"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-12 col-md-1 col-lg-2 d-none d-md-block">

  </div>

  <div id="fb-root"></div>
</div>
{% endblock %}

{% block script %}
{{ super() }}
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/ko_KR/sdk.js#xfbml=1&version=v2.6&appId=296453350689163";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>
<script>
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
</script>
{% endblock %}

app/templates/line_detail.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ line_name }}</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet">
  </head>

  <body class="grey lighten-4">

    <header>
      <div class="navbar-fixed">
        <nav class="light-green {% if line.get('tabs', [])|length > 1 %}z-depth-0{% endif %}">
          <div class="container">
            <div class="nav-wrapper">
              <a class="brand-logo center">{{ line.get('name') }}</a>

              <ul class="left">
                <li><a href="{{ url_for('__init__.line_list') }}"><i class="material-icons">list</i></a></li>
              </ul>

              <ul class="right">
                <li><a target="_blank" href="{{ line.get('reference_url') }}">출처</a></li>
              </ul>

            </div>
          </div>
        </nav>
      </div>
    </header>

    <main>
      <div class="light-green z-depth-1 {% if line.get('tabs', [])|length == 1 %} hide{% endif %}">
        <div class="container">
          <div class="row">
            <ul class="tabs light-green">
              {% for tab in line.get('tabs', []) %}
              <li class="tab col s3"><a class="white-text" href="#line-tab-{{ tab.get('id') }}">{{ tab.get('name') }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col m1 l2 hide-on-small-only">
            &nbsp;
          </div>

          <div class="col s12 m10 l8">
            {% for tab in line.get('tabs', []) %}
              <div id="line-tab-{{ tab.get('id') }}" class="col s12">

                <p class="center grey-text text-darken-2">{{ tab.get('time_description', '') }}</p>

                <div class="card white z-depth-0">
                  {% for time in tab.get('times', []) %}
                  <div class="card-content center">
                    {{ time }}
                  </div>
                  <div class="divider"></div>
                  {% endfor %}
                </div>

                <div class="card white z-depth-0">
                  {% for name, offset in tab.get('offsets', []) %}
                  <div class="card-content center">
                    {{ name }}, +{{ offset }}
                  </div>
                  <div class="divider"></div>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
          </div>

          <div class="col s12">
            <p class="center">
              <br/>
              <a href="mailto:yearnning@kaist.ac.kr" class="grey-text text-darken-2 underline">
                시간표가 잘못됐다면, 제보해주세요!
              </a>
              <br/>
              <span class="grey-text text-darken-2">({{ line.get('name') }} 시간표 업데이트: {{ line.get('update_date') }})</span>
            </p>
          </div>
        </div>

      </div>
    </main>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43718027-1', 'kaist.ac.kr');
  ga('send', 'pageview');

</script>

  </body>
</html>